---
title: "NY State Walkability Dashboard"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows
    navbar:
      - { title: "Home", href: "index.html", align: right }
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)
```

```{r data-setup, include=FALSE}
# Read data

walkability = read_csv("./data/merge_final.csv") 

walkability_clean = walkability %>% 
  separate(name, c("census_tract", "county", "state"), sep = ", ") %>% 
  drop_na(state)

walkability_tidy = walkability_clean %>% 
  filter(!is.na(state) &
         state == "New York" &
         !is.na(nat_walk_ind)
         ) %>% 
  group_by(county) %>% 
  summarise(walk = mean(nat_walk_ind))
  

#rmarkdown::render("dashboard.Rmd", output_format = "flexdashboard::flex_dashboard")

```




Row {data-height=800}
-----------------------------------------------------------------------

### Health outcome

```{r}
# renderPrint({
#   input[["outcome_choice"]]
# })

#renderPlotly(
walkability_clean %>% 
filter(!is.na(state) &
         state == "New York" &
         !is.na(nat_walk_ind)
         ) %>% 
  group_by(county, measure_id) %>% 
  summarise(walk = mean(nat_walk_ind),
            outcome = mean(data_value)) %>% 
  mutate(
    measure_id = replace(measure_id, measure_id == "HIGHCHOL", "High cholesterol"),
    measure_id = replace(measure_id, measure_id == "PHLTH", "Poor physical health"),
    measure_id = replace(measure_id, measure_id == "MHLTH", "Poor mental health"),
    measure_id = replace(measure_id, measure_id == "LPA", "No leisure physical activity"),
    measure_id = replace(measure_id, measure_id == "BPHIGH", "High blood pressure")
  ) %>% 
  plot_ly(x = ~county, 
          y = ~outcome, color = ~measure_id,
          type = "bar") %>% 
   add_trace(x = ~walkability_tidy$county, 
             y = ~walkability_tidy$walk,  
             type = 'scatter',  mode = 'lines+markers', name = 'Walkability index', 
             yaxis = "y2", color = I('black')
             ) %>% 
   layout(legend = list(x = 0.1, y = 180, orientation = 'h'),
          yaxis = list(title = '% with health outcome'),
          yaxis2=list(side="right",overlaying="y", title = "Average walkability index"),
          xaxis = list(title = 'County'),
          barmode = 'stack',
           shapes = list(
               list(type = "rect",
                    fillcolor = "navy", line = list(color = "navy"), opacity = 0.15,
                    x0 = -0.5, x1 = 62, xref = "x",
                    y0 = 0, y1 = 5.75, yref = "y2"),
               list(type = "rect",
                    fillcolor = "blue", line = list(color = "blue"), opacity = 0.15,
                    x0 = -0.5, x1 = 62, xref = "x",
                    y0 = 5.76, y1 = 10.5, yref = "y2"),
               list(type = "rect",
                    fillcolor = "teal", line = list(color = "teal"), opacity = 0.15,
                    x0 = -0.5, x1 = 62, xref = "x",
                    y0 = 10.51, y1 = 15.25, yref = "y2"),
               list(type = "rect",
                    fillcolor = "green", line = list(color = "green"), opacity = 0.15,
                    x0 = -0.5, x1 = 62, xref = "x",
                    y0 = 15.25, y1 = 20, yref = "y2")),
          annotations = list(
            list(x = 65,
                 y = 105,
                 font = list(size = 10),
                 text = "<b>Most<br>walkable</br></b>",
                 xref = "x",
                 yref = "y",
                 xanchor = "right",
                 yanchor = "bottom",
                 showarrow = FALSE,
                 textangle = 90),
            list(x = 65,
                 y = 75,
                 font = list(size = 10),
                 text = "<b>Above avg<br>walkable</br></b>",
                 xref = "x",
                 yref = "y",
                 xanchor = "right",
                 yanchor = "bottom",
                 showarrow = FALSE,
                 textangle = 90),
          list(x = 65,
                 y = 45,
                 font = list(size = 10),
                 text = "<b>Below avg<br>walkable</br></b>",
                 xref = "x",
                 yref = "y",
                 xanchor = "right",
                 yanchor = "bottom",
                 showarrow = FALSE,
               textangle = 90),
          list(x = 65,
                 y = 8,
                 font = list(size = 10),
                 text = "<b>Least<br>walkable</br></b>",
                 xref = "x",
                 yref = "y",
                 xanchor = "right",
                 yanchor = "bottom",
                 showarrow = FALSE,
               textangle = 90))
          )
#)

```

Row {.tabset  .tabset-fade}
-----------------------------------------------------------------------
### Race
```{r}
walkability_clean %>%
  mutate(percent_race = as.numeric(percent_race)) %>% 
  filter(!is.na(state) &
         state == "New York" &
         !is.na(nat_walk_ind) &
         !is.na(percent_race)
         ) %>% 
  group_by(county, race) %>% 
  summarise(walk = mean(nat_walk_ind),
            percent_race = mean(percent_race)) %>% 
  mutate(
    race = replace(race, race == "white", "White"),
    race = replace(race, race == "black", "Black"),
    race = replace(race, race == "aian", "American Indian/Alaska Native"),
    race = replace(race, race == "asian", "Asian"),
    race = replace(race, race == "2_plus", "≥2 races"),
    race = replace(race, race == "hispanic", "Hispanic/Latin American"),
    race = factor(race, levels = c("White", "Black", "Asian", "Hispanic/Latin American", 
                                   "American Indian/Alaska Native", "≥2 races"), ordered = TRUE)
  ) %>% 
  plot_ly(x = ~fct_reorder(county, percent_race), 
          y = ~percent_race, color = ~race,
          type = "bar") %>% 
   layout(legend = list(x = 0.1, y = 200, orientation = 'h'),
          yaxis = list(title = '% of each race category'),
          xaxis = list(title = 'County'),
          barmode = 'stack'
          )

```


### Median income
```{r}
walkability_clean %>%
  mutate(median_income = as.numeric(median_income)) %>% 
  filter(!is.na(state) &
         state == "New York" &
         !is.na(nat_walk_ind) &
         !is.na(median_income)
         ) %>% 
  group_by(county) %>% 
  summarise(walk = mean(nat_walk_ind),
            median_income = mean(median_income)) %>% 
  mutate(
    income = NA,
    income = replace(income, median_income <5000, "≤$5000"),
    income = replace(income, median_income >= 5000 & median_income < 10000, "$5000 - $9999"),
    income = replace(income, median_income >= 10000 & median_income < 15000, "$10000 - $14999"),
    income = replace(income, median_income >= 15000 & median_income < 20000, "$15000 - $19999"),
    income = replace(income, median_income >= 20000 & median_income < 25000, "$20000 - $24999"),
    income = replace(income, median_income >= 25000 & median_income < 35000, "$25000 - $34999"),
    income = replace(income, median_income >= 35000 & median_income < 45000, "$35000 - $44999"),
    income = replace(income, median_income >= 45000 & median_income < 55000, "$45000 - $54999"),
    income = replace(income, median_income >= 55000 & median_income < 65000, "$55000 - $64999"),
    income = replace(income, median_income >= 65000 & median_income < 75000, "$65000 - $74999"),
    income = replace(income, median_income >= 75000 & median_income < 100000, "$75000 - $99999"),
    income = replace(income, median_income >= 100000, "≥$100000"),
    income = factor(income, levels = c("≤$5000", "$5000 - $9999", "$10000 - $14999", "$15000 - $19999",
                                       "$20000 - $24999", "$25000 - $34999", "$35000 - $44999",
                                       "$45000 - $54999", "$55000 - $64999", "$65000 - $74999",
                                       "$75000 - $99999", "≥$100000"), ordered = TRUE),
    county = fct_reorder(county, median_income)
  ) %>% 
  plot_ly(x = ~county, 
          y = ~median_income, color = ~income,
          type = "bar") %>% 
   layout(legend = list(x = 0.1, y = 0.9, orientation = 'h'),
          yaxis = list(title = 'Median household income'),
          xaxis = list(title = 'County'),
          barmode = 'stack'
          )
```

### % Male
```{r}
walkability_clean %>%
  mutate(sex_male = as.numeric(sex_male)) %>% 
  filter(!is.na(state) &
         state == "New York" &
         !is.na(nat_walk_ind) &
         !is.na(sex_male)
         ) %>% 
  group_by(county) %>% 
  summarise(walk = mean(nat_walk_ind),
            sex_male = mean(sex_male)) %>% 
  mutate(county = fct_reorder(county, sex_male)) %>% 
  plot_ly(x = ~county, 
          y = ~sex_male, 
          # color = ~sex,
          type = "bar") %>% 
   layout(#legend = list(x = 0.1, y = 200, orientation = 'h'),
          yaxis = list(title = '% Male'),
          xaxis = list(title = 'County'),
          barmode = 'stack'
          )

```

### % Adults
```{r}
walkability_clean %>%
  mutate(age_18plus = as.numeric(age_18plus)) %>% 
  filter(!is.na(state) &
         state == "New York" &
         !is.na(nat_walk_ind) &
         !is.na(age_18plus)
         ) %>% 
  group_by(county) %>% 
  summarise(walk = mean(nat_walk_ind),
            age_18plus = mean(age_18plus)) %>% 
  mutate(county = fct_reorder(county, age_18plus)) %>% 
  plot_ly(x = ~county, 
          y = ~age_18plus, 
          type = "bar") %>% 
   layout(legend = list(x = 0.1, y = 200, orientation = 'h'),
          yaxis = list(title = '% Adults'),
          xaxis = list(title = 'County'),
          barmode = 'stack'
          )
```
