---
title: "Proposal"
output: github_document
---


##

#### Tentative project title: 
##### Walk the walk: the importance of walkability on health and wellbeing 

#### Team members (Walkaholics): 

* Winston Luhur (wel2110)
* Wenyan Ma (wm2460)
* Amy Yeung (ay2543) 
* Sophie Zhang (sjz2120)
* Shirley Liang (zl3118)

##

#### The motivation for this project:
Urban planning of most US cities was designed around cars and not walking, and not everywhere in the US is walkable for its residents. The recent pandemic has further emphasized the important role that accessible green space and walkable neighborhoods play in our individual and collective physical activity and mental wellbeing. We want to learn about the National Walkability Index published by the EPA, and how the index relates to health outcomes. We also would like to explore ways to improve the index to make it more comprehensive. As five *passionate walkaholics*🚶🏻‍♂️, we want to promote walking and hope more people will enjoy walking. 


##

#### The intended final products:

* Report
* Webpage (with interactive dashboard and maps)
* Screencast


##

#### The anticipated data sources: 
* Environmental Protection Agency's information on Walkability Index
* We will use BRFSS and US Census for health outcomes


##

#### The planned analyses / visualizations / coding challenges: 

* Interactive of walkability index
* Descriptive statistics of demographics by walkability categories (might need to merge w Census data)
  * Employment
  * Income 
  * Number of households
* Walkability, health outcomes, and other environmental features
  * Obesity 
  * Mental health 
  * Air quality / respiratory diseases
* Updating the Walkability Index
  * Including additional variables
  * Changing the weighting
  * R^2,  Interrater reliability
* Challenges
  * Uploading everything to GitHub
  * Visualization to scale 
  * Aggregating data across large datasets - need to check for correct merging


##

#### The planned timeline:

* Nov 12: Submit written proposal
* Nov 12-15: Solve git uploading issue
* Nov 15-18: Project review meeting
* Nov 17-22: Tidy data, Exploratory Data Analysis
* Nov 22-Dec 8: Finalize model (update walkability index) + visuals (interactive map and graphs, interactive dashboard), format website 
* Dec 8: Finalize webpage 
* Dec 9: Write report, record screencast
* Dec 10: Submit everything
