---
title: "Statistical Analysis"
output: github_document
---

<style>
div.blue { background-color:aliceblue; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

##### On this page XXXXX

</div>

<br>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
library(modelr)
library(betareg)
library(mgcv)
library(purrr)
library(broom)
library(mfx)

dataset = read_csv("./data/merge_final.csv")
```

```{r pivot-dataset}
regress_df = dataset %>% 
  pivot_wider(names_from = "race",
               values_from = "percent_race") %>% 
  pivot_wider(names_from = "measure_id",
              values_from = "data_value") %>% 
  janitor::clean_names() %>% 
  select(tractce, nat_walk_ind, csa_name, lat, long, sex_male, sex_female, age_18plus, median_income, white, black, aian, asian, x2_plus, hispanic, highchol, mhlth, lpa, phlth, bphigh) %>% 
  mutate(
    sex_male = as.numeric(sex_male)/100,
    age_18plus = as.numeric(age_18plus)/100,
    white = as.numeric(white)/100,
    black = as.numeric(black)/100,
    aian = as.numeric(aian)/100,
    asian = as.numeric(asian)/100, 
    x2_plus = as.numeric(x2_plus)/100, 
    hispanic = as.numeric(hispanic)/100, 
    highchol = highchol/100, 
    mhlth = mhlth/100, 
    lpa = lpa/100, 
    phlth = phlth/100, 
    bphigh = bphigh/100,
    median_income = as.numeric(median_income)
    ) %>%
  group_by(tractce) %>% 
  summarize(
    nat_walk_tract = mean(nat_walk_ind),
    sex_male = mean(sex_male),
    age_18plus = mean(age_18plus),
    white = mean(white),
    black = mean(black),
    aian = mean(aian),
    asian = mean(asian), 
    x2_plus = mean(x2_plus), 
    hispanic = mean(hispanic), 
    highchol = mean(highchol), 
    mhlth = mean(mhlth), 
    lpa = mean(lpa), 
    phlth = mean(phlth), 
    bphigh = mean(bphigh),
    median_income = mean(median_income),
    lat = lat,
    long = long
    ) %>% 
  unique()
```


```{r beta-test-code}
test = regress_df %>% 
  dplyr::select(!c("lat", "long")) %>% 
  mutate(walkable = ifelse(nat_walk_tract<10.5, "Less Walkable", "More Walkable")) %>% 
  unique()

# mod <- gam(highchol ~ nat_walk_tract + sex_male + age_18plus + black + median_income + s(lat, long, bs="gp", m=2),
#            family = betar(link='logit'),
#            data = regress_df)
# 
# summary(mod)
# 
# residual1_plot =
#     regress_df %>%
#     add_predictions(mod) %>%
#     add_residuals(mod) %>%
#     ggplot(aes(x = nat_walk_tract, y = resid)) +
#     geom_point(alpha = 0.3, size = 0.3) +
#     geom_smooth(se = FALSE, method = "lm")
# 
# residual1_plot

# mod_beta = betareg(mhlth ~ nat_walk_tract + sex_male + age_18plus + black, data = test)
# 
# summary(mod_beta)
# 
# residual_plot =
#     test %>%
#     add_predictions(mod_beta) %>%
#     add_residuals(mod_beta) %>%
#     ggplot(aes(x = nat_walk_tract, y = resid)) +
#     geom_point(alpha = 0.3) +
#     geom_smooth(se = FALSE, method = "lm")
# 
# residual_plot

# Beta regression model
chol = betareg(highchol ~ walkable + sex_male + age_18plus + black, data = test) %>% broom::tidy(conf.int=TRUE)
mental = betareg(mhlth ~ walkable + sex_male + age_18plus + black, data = test) %>% broom::tidy(conf.int=TRUE)
lpa = betareg(lpa ~ walkable + sex_male + age_18plus + black, data = test) %>% broom::tidy(conf.int=TRUE)
physical = betareg(phlth ~ walkable + sex_male + age_18plus + black, data = test) %>% broom::tidy(conf.int=TRUE)
bloodpres = betareg(bphigh ~ walkable + sex_male + age_18plus + black, data = test) %>% broom::tidy(conf.int=TRUE)

# Margins
chol_margin = betamfx(highchol ~ walkable + sex_male + age_18plus + black, data = test) %>% broom::tidy(conf.int=TRUE)
mental_margin = betamfx(mhlth ~ walkable + sex_male + age_18plus + black, data = test) %>% broom::tidy(conf.int=TRUE)
lpa_margin = betamfx(lpa ~ walkable + sex_male + age_18plus + black, data = test) %>% broom::tidy(conf.int=TRUE)
physical_margin = betamfx(phlth ~ walkable + sex_male + age_18plus + black, data = test) %>% broom::tidy(conf.int=TRUE)
bloodpres_margin = betamfx(bphigh ~ walkable + sex_male + age_18plus + black, data = test) %>% broom::tidy(conf.int=TRUE)

# Collate estimates into one data frame
modeldata = 
  chol %>% 
  filter(grepl('walk', term)) %>% 
  rbind(mental[2,]) %>% 
  rbind(lpa[2,]) %>% 
  rbind(physical[2,]) %>% 
  rbind(bloodpres[2,]) %>% 
  mutate(
    outcome = c("High Cholesterol", "Mental Health", "Physical Activity", "Physical Health", "High Blood Pressure"),
    OR = exp(estimate),
    lowlim = exp(conf.low),
    highlim = exp(conf.high)
  )

marginsdata = 
  chol_margin %>% 
  filter(grepl('walk', term)) %>% 
  rbind(mental_margin[1,]) %>% 
  rbind(lpa_margin[1,]) %>% 
  rbind(physical_margin[1,]) %>% 
  rbind(bloodpres_margin[1,]) %>% 
  mutate(
    outcome = c("High Cholesterol", "Mental Health", "Physical Activity", "Physical Health", "High Blood Pressure")
  )
```

```{r reference-code}
# baltimore_glm =
#  baltimore_df %>%
#  glm(solved ~ victim_age + victim_sex + victim_race,
#    data = .,
#    family = binomial()) %>%
#  broom::tidy() %>%
#  janitor::clean_names() %>%
#  mutate(OR = exp(estimate),
#         CI_lower = exp(estimate - 1.96*std_error),
#         CI_upper = exp(estimate + 1.96*std_error))
# baltimore_glm
# 
# unsolved_all = homicide_city_state %>% 
#   mutate(
#     prop_test = map2(.x = unsolved, .y = total, ~prop.test(x = .x, n = .y)),
#     prop_est = map(.x = prop_test, ~broom::tidy(.x))
#   ) %>% 
#   select(-prop_test) %>% 
#   unnest(prop_est) %>% 
#   select(city_state, estimate, conf.low, conf.high) %>% 
#   mutate(across(where(is.numeric), function(x) x*100))
```


