---
title: "Data Cleaning"
output: github_document
---
<details>
  <summary>Click to show all code chunks</summary>
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)

```

## Walkability Data
```{r}
walkability_raw = read_csv("./data/EPA_SmartLocationDatabase_V3_Jan_2021_Final.csv")

walkability_new = walkability_raw %>% 
  janitor::clean_names() %>% 
  mutate(statefp = str_pad(statefp, width = 2, pad = "0"),
         countyfp = str_pad(countyfp, width = 3, pad = "0"),
         tractce = str_pad(tractce, width = 6, pad = "0"),
         fips = str_c(statefp, countyfp, tractce, blkgrpce, sep = "")) %>% 
  select(fips, everything(), -objectid)
  
walkability_clean = walkability_new %>% 
  select(fips, statefp, countyfp, tractce, blkgrpce, nat_walk_ind, csa_name) %>% 
  mutate(location_name = str_c(statefp, countyfp, tractce, sep = ""))
  
```

## Health Outcome Data - BRFSS

```{r}
# raw data with all health outcomes
health_df = read_csv("./data/PLACES__Local_Data_for_Better_Health__Census_Tract_Data_2022_release.csv")

health_new = health_df %>% 
  janitor::clean_names() %>%
  mutate(location_name = str_pad(location_name, width = 11, pad = "0"),
         geolocation = str_replace(geolocation, "^POINT ", ""),
         geolocation = str_replace(geolocation, "^\\(", ""),
         geolocation = str_replace(geolocation, "\\)$", "")) %>% 
  separate(geolocation, into = c("lat", "long"), sep = " ")
  
```

## Demographic Data - ACS 2020
### Age and Race
```{r}
demo_raw = read_csv("./data/ACSDP5Y2020.DP05-Data.csv")

demo_clean = demo_raw %>% 
  slice(-1) %>% 
  janitor::clean_names() %>%
  select(-ends_with(c("ea", "m", "ma"))) %>% 
  mutate(geo_clean = geo_id, 
         geo_clean = str_replace(geo_clean, "^1400000US", "")) %>% 
  select(geo_clean, dp05_0002pe, dp05_0003pe, dp05_0021pe, dp05_0037pe, dp05_0038pe, dp05_0039pe, dp05_0044pe, dp05_0058pe, dp05_0071pe)
```

### Median household income 
```{r}
income_raw = read_csv("./data/ACSST5Y2020.S1903-Data.csv")

income_clean = income_raw %>% 
  janitor::clean_names() %>%
  select(geo_id, name, s1903_c03_001e) %>% 
  slice(-1) %>% 
  mutate(geo_clean = geo_id, 
         geo_clean = str_replace(geo_clean, "^1400000US", "")) %>% 
  select(geo_clean, everything())
```


## Further cleaning
```{r}
# for health outcome, we are focusing on 5 outcomes that are likely to be related to walkability 

health_clean = health_new %>% 
  filter(measure_id == c("BPHIGH", "PHLTH", "LPA", "MHLTH", "HIGHCHOL")) %>% 
  select(location_name, lat, long, measure, data_value, data_value_type, data_value_unit, measure_id)
```


##Merge
```{r}
# merging walkability and health outcomes
merge1 = full_join(x = walkability_clean, y = health_clean, by = "location_name")

#mergeing demographic into one df - age&race + median household income
merge2 = full_join(demo_clean, income_clean, by = "geo_clean")
  
merge2 = merge2 %>% 
  mutate(location_name = geo_clean) 

# merge merge1 and merge2
merge_final = full_join(x = merge1, y = merge2, by = "location_name")

merge_final = merge_final %>% 
  rename(sex_male = dp05_0002pe,
         sex_female = dp05_0003pe,
         age_18plus = dp05_0021pe,
         race_white = dp05_0037pe,
         race_black = dp05_0038pe,
         race_aian = dp05_0039pe,
         race_asian = dp05_0044pe,
         race_2_plus = dp05_0058pe,
         race_hispanic = dp05_0071pe,
         median_income = s1903_c03_001e) %>% 
  pivot_longer(names_to = "race",
               values_to = "percent_race",
               cols = starts_with("race"),
               names_prefix = "race_") %>% 
  pivot_wider(names_from = "measure_id",
               values_from = "data_value") %>% 
  select(-data_value_type, -data_value_unit)

write_csv(merge_final, "./data/merge_final.csv")

```

## Plot try
```{r}
merge_final %>%
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~nat_walk_ind, alpha = 0.5)
```


## Plot more and failed
```{r}
library(maptools)
library(spatstat)
library(sf)

#map_try = st_read("./data/cb_2020_us_tract_500k/cb_2020_us_tract_500k.shp")

#plot(map_try["geometry"])
```

## Plot more and successed
### on county
```{r}
library(rjson)
library(leaflet)

merge_plot = merge_final %>% 
  mutate(fips_county = str_c(statefp, countyfp)) %>% 
  group_by(fips_county) %>% 
  summarise(ind_mean = mean(nat_walk_ind))

url = 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'

counties = rjson::fromJSON(file = url)

g = list(scope = 'usa',
         projection = list(type = 'albers usa'),
         showlakes = TRUE,
         lakecolor = toRGB('white'))

fig = plot_ly()

fig = fig %>% 
  add_trace(type = "choropleth",
            geojson = counties,
            locations = merge_plot$fips_county,
            z = merge_plot$ind_mean,
            colorscale = "Viridis",
            zmin = 1,
            zmax = 16,
            marker = list(line = list(width = 0)))

#fig = fig %>% colorbar(title = "National Walkability Index")

fig = fig %>%
  layout(title = "National Walkability Index in the US")

fig = fig %>% 
  layout(geo = g)

fig

#mytext = paste("Male Percentage: ", merge_plot$dp05_0002pe, "<br/>") %>% 
#  lapply(htmltools::HTML)

#leaflet(fig) %>% 
#  add_polygons(label = mytext)

```

```{r testing-hovertext}
library(rjson)
library(leaflet)

fig_hover_test = plot_ly()

# creating new dataset with health measures by county 
# NEED TO GET RID OF NAs WHEN PIVOTING
hover_test_df = merge_final %>%
  mutate(fips_county = str_c(statefp, countyfp)) %>% 
  group_by(fips_county, measure_id) %>%
  summarise(county_hlth = round(mean(data_value, na.rm = TRUE), 1)) %>%
  pivot_wider(names_from = "measure_id", values_from = "county_hlth") %>% 
  janitor::clean_names()

# adding variable for hovertext
hover_test_df$hover <- with(hover_test_df, 
                            paste('<br>',
                                                 "% Health Outcomes (by County):", '<br>',
                                                 "High Cholesterol:", highchol, '<br>',
                                                 "Physical Inactivity:", lpa, '<br>',
                                                 "Mental Health:", mhlth, '<br>',
                                                 "Physical Health:", phlth, '<br>',
                                                 "High BP:", bphigh))

# Testing choropleth with hovertext of health outcomes by county
fig_hover_test = plot_ly()

fig_hover_test = fig_hover_test %>% 
  add_trace(type = "choropleth",
            geojson = counties,
            locations = merge_plot$fips_county,
            z = merge_plot$ind_mean,
            text = hover_test_df$hover,
            colorscale = "Viridis",
            zmin = 1,
            zmax = 16,
            marker = list(line = list(width = 0)))

fig_hover_test = fig_hover_test %>%
  layout(title = "National Walkability Index in the US")

fig_hover_test = fig_hover_test %>% 
  layout(geo = g)

fig_hover_test

```



### Clustering analysis for walkability

```{r}
library(rgeoda)
library(sf)
library(tmap)
library(tidyverse)
library(leaflet)


# Read-in csv
cluster_map <- st_read("./data/cluster_analysis/map_with_everything.shp")

#cluster_map_check = cluster_map %>% 
#  group_by(STUSPS) %>% 
#  summarize(count = sum(is.na(nat_walk_i)))

cluster_map_FL = cluster_map %>% 
  janitor::clean_names() %>% 
  mutate(nat_walk_i = as.numeric(nat_walk_i),
        nat_walk_i = round(nat_walk_i, digits = 1)) %>% 
  filter(stusps == "NY",
         namelsadco %in% c("Bronx County", "Kings County", "New York County", "Queens County", "Richmond County")) %>% 
  rename(median_income = s1903_c03) %>% 
  mutate(median_income = as.numeric(median_income))

cluster_map_NY = cluster_map_FL[!is.na(cluster_map_FL$nat_walk_i),]
  

# Queen 1st order weights matrix 
queen_w <- queen_weights(cluster_map_NY, order = 1)

summary(queen_w)


# Local Moran's I
lisa <- local_moran(queen_w, cluster_map_NY["nat_walk_i"],
                    permutations = 9999)

# What's contained under the "lisa" object?
names(lisa)

lisa$GetClusterIndicators()

# Get cluster column and join it to zip shp
cluster_map_NY$cluster <- as.factor(lisa$GetClusterIndicators())
str(cluster_map_NY)

# Add labels to clusters
levels(cluster_map_NY$cluster) <- lisa$GetLabels()

# Map clusters
#tm_shape(cluster_map) +
#  tm_fill("cluster") 

# We need the GeoDa colors!
lisa_colors <- lisa_colors(lisa)


# Recode clusters using tidyverse (dyplr)
cluster_map_NY %>% 
  mutate(cluster = recode_factor(.x = cluster,
                                  `Undefined` = "Not significant",
                                  `Isolated` = "Not significant")) -> cluster_map_NY

# Map new categories 
tmap_mode("view")

tm_basemap("CartoDB.Positron") +
  tm_shape(cluster_map_NY) +
  tm_polygons(col ="cluster", 
              palette=  c("#eeeeee", 
                      "#FF0000",
                      "#0000FF",
                      "#a7adf9",
                      "#f4ada8"),
              alpha = .8,
              title = "Clusters",
              border.col = "black",
              border.alpha = .9) 
```

##median household income
```{r}
# Local Moran's I
lisa <- local_moran(queen_w, cluster_map_NY["median_income"],
                    permutations = 9999)

# What's contained under the "lisa" object?
names(lisa)

# Get cluster column and join it to zip shp
cluster_map_NY$cluster <- as.factor(lisa$GetClusterIndicators())
str(cluster_map_NY)

# Add labels to clusters
levels(cluster_map_NY$cluster) <- lisa$GetLabels()

# Map clusters
#tm_shape(cluster_map) +
#  tm_fill("cluster") 

# We need the GeoDa colors!
lisa_colors <- lisa_colors(lisa)


# Recode clusters using tidyverse (dyplr)
cluster_map_NY %>% 
  mutate(cluster = recode_factor(.x = cluster,
                                  `Undefined` = "Not significant",
                                  `Isolated` = "Not significant")) -> cluster_map_NY

# Map new categories 
tm_shape(cluster_map_NY) +
  tm_polygons(col ="cluster", 
              palette=  c("#eeeeee", 
                      "#FF0000",
                      "#0000FF",
                      "#a7adf9",
                      "#f4ada8"),
              alpha = .8,
              title = "Clusters",
              border.col = "black",
              border.alpha = .9)


tm_shape(cluster_map_NY) +
  tm_polygons(col = "median_income", 
              style = "jenks",
              n = 5) 
```


```{r}
bi_lisa <- local_bimoran(queen_w, cluster_map_NY[c("nat_walk_i", "median_income")],
                    permutations = 9999)

names(bi_lisa)

bi_lisa$labels
```

</details>


